language: php

sudo: false
dist: trusty

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

before_install:
  # Add Redis & Memcached extensions
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  # Memcache to be removed in when PHP 5 is dropped
  - |
    if [[ $TRAVIS_PHP_VERSION =~ ^5 ]]; then
        echo "extension = memcache.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    fi
  # Remove PHP CS Fixer for PHP 5.5 since it requires PHP 5.6
  - if [[ $TRAVIS_PHP_VERSION == "5.5" || $TRAVIS_PHP_VERSION == "hhvm" ]]; then composer remove friendsofphp/php-cs-fixer --dev --no-update; fi

before_script:
  - composer self-update || true
  - composer install

script:
  # PHPUnit
  - vendor/bin/phpunit --coverage-clover=coverage.xml
  # PHP CodeSniffer
  - vendor/bin/phpcs -p --report=summary
  # PHP CS Fixer (if >=5.6)
  - if [[ $TRAVIS_PHP_VERSION != "5.5" && $TRAVIS_PHP_VERSION != "hhvm" ]]; then vendor/bin/php-cs-fixer fix --dry-run; fi

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - vendor
    - $COMPOSER_CACHE_DIR
